Return the highest enrichment version seen on MarkLogic
nationalarchives/ds-caselaw-custom-api-client pull request #525
Opened 2024-01-10 12:23 UTC by dragon-dxw

Does not necessarily reflect the version number in Enrichment. This might lead to scenarios where bulk enrichment is stalled until a single successful manual or new-document enrichment occurs.

2024-01-18 16:01 UTC, jacksonj04 requested changes
Looks like missing a file in the commit.

2024-01-18 16:01 UTC, jacksonj04 commented on src/caselawclient/Client.py
> +                    "get_highest_enrichment_version.xqy",
I think this is missing!

2024-01-23 12:39 UTC, dragon-dxw commented on src/caselawclient/Client.py
> +                    "get_highest_enrichment_version.xqy",
Added! Good spot.

2024-01-23 12:41 UTC, jacksonj04 approved these changes

2024-01-23 12:47 UTC, merged